### ISSUE TITLE
Problem with compile on FreeBSD 13.2

### ISSUE THREAD

**Issue by FuckInfernal** [unixwork/xnedit#138]
Downloaded version 1.5.3
Then,
`$cd xnedit`
`$make freebsd`
Error log1.txt:
```
`cc  -O -I/usr/local/include -I/usr/local/include/X11 -DUSE_LPR_PRINT_CMD -DUSE_XMIM `pkg-config --cflags xft fontconfig` -c textfield.c -o textfield.o
/bin/sh: pkg-config: not found
In file included from textfield.c:23:
In file included from ./textfieldP.h:30:
In file included from ./../source/textDisp.h:36:
/usr/local/include/X11/Xft/Xft.h:40:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>`
```
[log1.txt](https://github.com/unixwork/xnedit/files/14792887/log1.txt)
Then, attempt to bypass
`ln -s /usr/local/include/freetype2/ft2build.h /usr/local/include/ft2build.h`
`ln -s /usr/local/include/freetype2/freetype/ /usr/local/include/freetype`
Result - following error:
```
`ld: error: unable to find library -liconv
ld: error: unable to find library -lpcre
ld: error: unable to find library -lXm
ld: error: unable to find library -lXt
ld: error: unable to find library -lSM
ld: error: unable to find library -lICE
ld: error: unable to find library -lX11
ld: error: unable to find library -lXrender
ld: error: unable to find library -lXext
cc: error: linker command failed with exit code 1 (use -v to see invocation)
`
```
[log2.txt](https://github.com/unixwork/xnedit/files/14792912/log2.txt)
Then, try to configure makefile. Change line in Makefile.freebsd:
old: LIBS= -liconv -lpcre -lm -lXm -lXt -lSM -lICE -lX11 -lXrender -lXext `pkg-config --libs xft fontconfig`
new:LIBS= -L/usr/local/lib -lXm -lXt -lX11 -lXmu -lXrender -lXft -lfontconfig -lm -lXpm -ljpeg -lpng -liconv
Result - following error:
```
ld: error: undefined symbol: pcre_compile
>>> referenced by ec_glob.c
>>>               ec_glob.o:(ec_glob) in archive ../util/libNUtil.a
>>> referenced by ec_glob.c
>>>               ec_glob.o:(ec_glob) in archive ../util/libNUtil.a

ld: error: undefined symbol: pcre_exec
>>> referenced by ec_glob.c
>>>               ec_glob.o:(ec_glob) in archive ../util/libNUtil.a
>>> referenced by ec_glob.c
>>>               ec_glob.o:(ec_glob) in archive ../util/libNUtil.a

ld: error: undefined symbol: pcre_free
>>> referenced by ec_glob.c
>>>               ec_glob.o:(ec_glob) in archive ../util/libNUtil.a
>>> referenced by ec_glob.c
>>>               ec_glob.o:(ec_glob) in archive ../util/libNUtil.a
>>> referenced by ec_glob.c
>>>               ec_glob.o:(ec_glob) in archive ../util/libNUtil.a
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```
[log3.txt](https://github.com/unixwork/xnedit/files/14792937/log3.txt)
No chance!

**Comment by unixwork** [comment]
I think you need to install many packages/ports to compile xnedit. Try to install the following packages:

	pkgconf
	open-motif
	libiconv
	pcre

If you are using the newest code from the git repository, you don't need pcre.

**Comment by FuckInfernal** [comment]
Thank you! Installing pkg-conf helped

**Comment by FuckInfernal** [comment]
Thank you! Installing pkgconf helped
